version: '3'

services:
  mern:
    depends_on:
      - mongo
    build:
      context: mern
      dockerfile: Dockerfile
    env_file: secrets/local.secrets
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./mern/packages:/srv/src/packages
      - ./mern/scripts:/srv/src/scripts
    links:
      - mongo
  mongo:
    image: mongo:3.4.2
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
