# Currently this is not working, need to spend some time
# to see what configurations are necessary to run docker-compose
# in circleci v2, it needs to support docker-compose v3
version: 2
jobs:
  build:
    executorType: machine
    working_directory: ~/src
    environment:
      NODE_ENV: 'test'
    steps:
      - checkout
      - setup_docker_engine
      # Generate necessary secrets files
      - run:
          name: Add blank local secrets files
          command: |
            touch ./secrets/local.secrets
      # Run our test command
      - run:
          name: Run uor Test command
          command: |
            docker-compose run web npm test
